baseURL = 'https://mcasrom.github.io/perspectiva_global/'
languageCode = 'es-es'
title = 'Perspectiva Global: Cr√≥nicas del Nuevo Orden'
theme = 'PaperMod'


[params]
    env = "production"
    title = "Perspectiva Global"
    description = "Cr√≥nicas de un nuevo orden mundial"
    author = "M. Castro"
    
    # Est√©tica y Funcionalidad
    defaultTheme = "auto" # Cambia entre luz/oscuridad seg√∫n el sistema
    showCodeCopyButtons = true
    displayFullContent = false
    ShowReadingTime = true
    ShowShareButtons = true
    ShowPostNavLinks = true
    
    [params.homeInfoParams]
        Title = "Perspectiva Global üåç"
        Content = "An√°lisis soberano sobre geopol√≠tica, tecnolog√≠a y el gran tablero mundial. Publicado desde Debian."

    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/mcasrom"
